### PR TITLE
New languaje support ES-es

### PR DESCRIPTION
**Pull request by SofiaRedmond**
**_New translation into Spanish, it would be good if I could access a copy of the application with the language installed to correct some context in the translation._**

[strings [ES-es].zip](https://github.com/oO0oO0oO0o0o00/blocktopograph/files/8527097/strings.ES-es.zip)

### CODE REVIEW

**Comment by oO0oO0oO0o0o00** [comment]
SubChunk terrain for 1.2.13+ is handled in com.mithrilmania.blocktopograph.chunk.terrain.V1d2d13TerrainSubChunk.java.

Classes for terrain and chunks are in packages named `terrain` and `chunk` and are easy to find. Code for older versions was commented out because at the time I was only able to refactor the part for the new version.

Feel free to work on your own for now. Mine is not the source repository as well as yours. Thanks, meow~

**Comment by MiemieMethod** [comment]
> SubChunk terrain for 1.2.13+ is handled in com.mithrilmania.blocktopograph.chunk.terrain.V1d2d13TerrainSubChunk.java.
> 
> Classes for terrain and chunks are in packages named `terrain` and `chunk` and are easy to find. Code for older versions was commented out because at the time I was only able to refactor the part for the new version.
> 
> Feel free to work on your own for now. Mine is not the source repository as well as yours. Thanks, meow~

@NguyenDuck Maybe you didn't subscribe this thread (((

**Comment by oO0oO0oO0o0o00** [comment]
@MiemieMethod 蹭蹭w

**Comment by oO0oO0oO0o0o00** [comment]
...

**Pull request closed without merging**
