### PR TITLE
Added a normal Russian translation.

### PR DESCRIPTION
**Pull request by Max-RM**
Hi. 

I decided to check the Russian translation that was in the application now, it's just terrible, it's like it was done through an auto translator and the meaning of the words is sometimes wrong.

I created my own translation made manually (despite the fact that I had used only English translation for many years before) now the translation is much better. 

yes, I know that the UI of the program is already intuitive and the user does not even need to know English to understand the UI. nevertheless, this translation is intended for beginners who do not know English at all.

also, I was unable to translate several phrases in the app, as they literally do not exist in ...values/strings.xml and ...values-ru/strings.xml.  and I noticed that the translator into Chinese faced the same problem and also could not translate the same phrases.

IMG_20230117_164604
IMG_20230117_164628
IMG_20230117_164454

So I finished this translation today for the best NBT editor for Android OS. 

I do not guarantee that my translation is perfect and I will probably correct or add something in the future.

### CODE REVIEW

**Comment by Max-RM** [comment]
[strings.xml.zip](https://github.com/oO0oO0oO0o0o00/blocktopograph/files/10434699/strings.xml.zip)

**Comment by BengbuGuards** [comment]
Good work!

**Comment by Max-RM** [comment]
> Good work!

Thx

**Comment by oO0oO0oO0o0o00** [comment]
Good work~ Maybe you can build the apk with the updated language file on your own. Let us know if there's any problem meow~

**Comment by Max-RM** [comment]
> Good work~ Maybe you can build the apk with the updated language file on your own. Let us know if there's any problem meow~

no problem, these apks are already made.
https://github.com/Max-RM/Blocktopograph_-Ru-translate-/releases

**Comment by oO0oO0oO0o0o00** [comment]
> > Good work~ Maybe you can build the apk with the updated language file on your own. Let us know if there's any problem meow~
> 
> no problem, these apks are already made. https://github.com/Max-RM/Blocktopograph_-Ru-translate-/releases

Another thing. Just remembered that the most active fork of the repository is now https://github.com/NguyenDuck/blocktopograph .

**Comment by Max-RM** [comment]
> > > Good work~ Maybe you can build the apk with the updated language file on your own. Let us know if there's any problem meow~
> > 
> > 
> > no problem, these apks are already made. https://github.com/Max-RM/Blocktopograph_-Ru-translate-/releases
> 
> Another thing. Just remembered that the most active fork of the repository is now https://github.com/NguyenDuck/blocktopograph .

IK. I'll contact him later about the Russian translation.

**Comment by Max-RM** [comment]
Btw. 

Blocktopograph has a drop-down list for ldb keys

(player_...) 

but there are no drop-down lists for ldb keys

(structuretemplate_mystructure:...)

and 

(map_...) 

Can you add this?

**Comment by oO0oO0oO0o0o00** [comment]
I kittenally won't consider any new feature/optimization unless the app can somehow work again on devices of the majority of users. Since the Google guys have stopped to agree that smartphones and/or tablets shall be viewed as "PC Lite", and had introduced  incresingly many changes preventing "apps" to behave like "programs" but rather webpages, I'd say it's impossible. The Cat's advice is that we'd simply (though pratically not simple enough) move to PC. There're enough tools for both Java and Bedrock edition already.

**Comment by Max-RM** [comment]
> I kittenally won't consider any new feature/optimization unless the app can somehow work again on devices of the majority of users. Since the Google guys have stopped to agree that smartphones and/or tablets shall be viewed as "PC Lite", and had introduced incresingly many changes preventing "apps" to behave like "programs" but rather webpages, I'd say it's impossible. The Cat's advice is that we'd simply (though pratically not simple enough) move to PC. There're enough tools for both Java and Bedrock edition already.

well, the fact that MCPE changed the storage location of the worlds in the new versions does not mean that the old versions of MCPE changed their storage location of the worlds, it remained true. there are also methods for transferring the worlds of new versions from ...Android/data... to other folders so that Blocktopograph has access to them. or another way, here https://github.com/oO0oO0oO0o0o00/blocktopograph/pull/10#issuecomment-1399421689 I described how to fix Mojang's idiotic decision to change the storage location of worlds without being able to choose the old path of storing worlds.

**Pull request merged**
